version: '3'

services:
    php:
        image: sheepsoftcz/php:8.0
        volumes:
          - ./:/var/www/html

    composer:
        image: composer:latest
        command: install --ignore-platform-reqs
        volumes:
          - ./:/app
          - ~/.composer/cache:/tmp/cache
